### PR TITLE
start line from first point, not 0 0

### PR DESCRIPTION
**Pull request by akostadinov**
Presently a colored line is drawn from coordinates 0x0 to
the first data point but this is ugly and serves no purpose.

With this patch, the Line chart starts from the first data point instead.

### CODE REVIEW

**Comment by t12nslookup** [comment]
how does this work with "area fill" turned on?  do you know how this behaves with more than one "@config[:fields]" in the data?

**Comment by akostadinov** [comment]
I didn't think about area fill. I'll check line example tomorrow. But what do you mean with 

> more than one "@config[:fields]"

Do you have such an example?

**Comment by t12nslookup** [comment]
Not on hand. I just went through the code looking at things that might trip your change. If I get time, I'll try to sort one, but it won't be before the weekend

**Comment by akostadinov** [comment]
In examples I only see `@config[:fields]` set to an array. What else can it be set to and what should that achieve?

Sure, whenever you can.

**Comment by lumean** [comment]
same as for the other PR, please also regenerate all examples so we can see the diff in resulting graphs, also feel free to add additional examples or tests in the test folder. It's been a while since I've worked last on this project. Unfortunately, testing always was a bit of manual verification of generated graphs and thinking about corner cases. I tried to automate it a bit via percy.io.

**Comment by akostadinov** [comment]
I regenerated.

I have some ideas about tests that would cover my limited use case. Once I get my changes approved on the project I work on, I can add tests for the specific things I needed here as well.

btw, what I found really nice when using SVG is that I can edit the result to achieve the end goal unlike with other libraries which generate raster images, where it is much harder to workaround their limitations.

**Comment by akostadinov** [comment]
FYI you can see the difference with and without patch with `examples/line.svg`. Where previously points go from 0 to their value and it is not nice IMO

**Comment by lumean** [comment]
thanks a lot! sorry for not being very active here :-/

**Pull request merged**
