### PR TITLE
fixed my errors, and checked properly this time

### PR DESCRIPTION
**Pull request by t12nslookup**
WARNING:  a lot of these changes are good, and useful for everyone, but I have moved the shape of the point to a "shape" array in the "data" hash, rather than in the "description", as the "description" is also used in the popup labels.

I would like to move the "shape" to the SVG "Icons", but that's work for another day/year/life

### CODE REVIEW

**Comment by t12nslookup** [comment]
example of graph with over 5k points on it:

image

**Comment by lumean** [comment]
I will need to revisit the breaking change with the shape vs description. Can you provide a simple example making use of the newly added parameters so I can add it as unit test?
I think there is some missing documentation, I will merge the changes but revert some variable renaming. Then also align usage of DataPoint class. E.g. Line plot uses hardcoded circles vs  Plot uses dynamic datapoints

**Comment by t12nslookup** [comment]
I can try and make it into 2 branches, if that helps.

The main difference for me is that I have a chromatogram that changes the
shape and positions of the point differently, but the label should only
show the value, or an error, in this case, not something that dictates the
shape ...

I could make the change so that it uses shape, then description if shape is
null? This shouldn't cause breakage, but makes it an enhancement?

Jon

**Comment by lumean** [comment]
yes, please let me do a proposal, hope to be done with it tonight. I'll also need to add some additional documentation - mainly for my future self :-) .... took me way to long to understand your changes.

**Comment by t12nslookup** [comment]
It'll be tomorrow at the earliest. I've had a couple of glasses of wine,
and I don't want to make mistakes :-)

Let me know how you want it broken down if it helps and I'll get to it.

Jon

**Comment by lumean** [comment]
please check my latest commit incl example, will need to revert css change in DataPoint tomorrow

**Comment by t12nslookup** [comment]
Ta.

I'll rebase, and work on caching and clearing better, and check whether or
not it's easier for me to override in my objects that inherit from yours.
It might well be that some of my changes are not needed, after some of your
latest are done.

I'll share my separate SVG code soon, but it's not complete.

Thanks again,

Jon

**Pull request merged**
