### PR TITLE
anchor right y labels

### PR DESCRIPTION
**Pull request by akostadinov**
in default style, there is

```
.yAxisLabels{
  text-anchor: end;
  fill: #000000;
  font-size: #{y_label_font_size}px;
  font-family: "Arial", sans-serif;
  font-weight: normal;
}
```

but that is overridden to `middle` in `Graph.rb`.

I think it makes more sense to have `end` anchoring for y labels as it
looks more orderly and other libraries do so.

So this patch changes y labels to anchor `end`.

This doesn't work very well with `stagger`. But even without this patch
`stagger_y_labels` is not really usable, at least what I see on my graph.
So it is probably ok to merge. Unless somebody has time and motivation to
make this configurable.

### CODE REVIEW

**Comment by t12nslookup** [comment]
While I can see your point, I generally inherit from this and override the "get_css" function, which you could do in order to get the CSS you desire?

Otherwise, it might be better to add your extra CSS change to the individual models, in their "get_css" method?

**Comment by akostadinov** [comment]
I'm not sure what you mean with overriding `get_css` but `text.attributes["style"] = ...` is the lesser issue. I see no point to hardcode it there if intention is to support user choice of the anchor.

The reason to keep it hardcoded is `x = ...`. Because `x` needs to be different depending on the anchor (middle, end or start). And it doesn't seem very straightforward to me to figure out what user has set in styles to set `x` accordingly.

**Comment by lumean** [comment]
When I find time I need to look through the test graphs and see if something breaks by the change.  Could you maybe regenerate the all testgraphs and commit those with your change?  I saw that meanwhile github directly shows the graphs in the "Files changed" Tab.

**Comment by akostadinov** [comment]
Regenerated. I must say with longer labels and with non-mono fonts, it is more apparent that right anchoring appears more orderly.

**Comment by lumean** [comment]
yes agree, looks better and also removes the calculation of the anchor coordinates.

**Comment by lumean** [comment]
published new version, I merged your suggestion, thanks!

**Pull request closed without merging**
