### PR TITLE
X divisions

### PR DESCRIPTION
**Pull request by t12nslookup**
An addition of fixing the "scale_divisions" for based on the max_x calculation, for the Plot.rb and TimeSeries.rb files, trying to make sure that there is neither a large gap at the right, or data overflowing the end of the chart.

### CODE REVIEW

**Comment by lumean** [comment]
thanks

**Comment by t12nslookup** [comment]
thank you :)

**Comment by lumean** [comment]
sorry will need to revisit some of these changes, it broke some other graphs in the tests:
https://percy.io/a5e00e98/svg-graph2/builds-next/8228082/changed/467841798?browser=firefox&browser_ids=9%2C14&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=1280

you can run  `bundle exec rake`  and then check  `plot_test_plot_axis_too_short.html`  in the test folder under test/percy.io_staticpages

**Comment by t12nslookup** [comment]
Ta, will look at tomorrow

**Comment by t12nslookup** [comment]
It won't let me see that Percy link, with an access denied message.

I'll run the tests, recreate the images and compare.  The issue I'm trying
to work around is in the rounding/ceiling of the min/max/segments, and I'm
probably better off seeing if I can fix it properly, rather than with
increment changes.

My email is t12nslookup@gmail.com, for that service, if it makes any
difference.

Jon

**Comment by t12nslookup** [comment]
new pull request added.

apart from "plot_test_plot_axis_too_short.html" all the charts appear to be
appropriately sized, and I'm assuming that that plot is supposed to be
incorrect.

Hopefully I've not screwed any other charts up.  my variants appear to be
working correctly.  I haven't modified the "TimeSeries.rb" chart to use the
same sort of formula as the "Plot.rb", so there is a possibility that this
problem may exist in small date ranges (< 1 week), where "scale_x_integers"
is set, but hopefully the (x_scale_division/10) might provide enough
padding.

Thanks for putting up with me :)

Jon

**Pull request merged**
